import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/context/cartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <CartProvider>
         {children} 
        </CartProvider>  
      </body>
    </html>
  );
}
