import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/context/cartContext";
import {FilterProvider} from "@/context/filterContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <FilterProvider>
          <CartProvider>
           {children} 
          </CartProvider>  
        </FilterProvider>
      </body>
    </html>
  );
}
